Feature/preb 26 enable with credentials request
dmdconnects/Prebid.js pull request #12
Opened 2021-06-17 18:02 UTC by Jayaharshak

2021-06-17 18:10 UTC, awerlang requested changes

2021-06-17 18:10 UTC, awerlang commented on modules/dmdIdSystem.js
> +            if (response & response.dgid) {
@Jayaharshak Do you mean `response && response.dgid`? Note the boolean vs bitwise operator.

2021-06-17 18:10 UTC, awerlang commented on modules/dmdIdSystem.js
> +                responseObj = JSON.parse(response.dgid);
@Jayaharshak What's the expected format for `dgid`? Is it a nested object or a string? If string `JSON.parse()` would fail.

2021-06-17 21:14 UTC, awerlang approved these changes

2021-06-18 14:49 UTC, matthewfitz approved these changes

2021-06-18 14:51 UTC, merged