feat(module):dmd user id module[PREBID-1]
dmdconnects/Prebid.js pull request #2
Opened 2021-04-15 19:32 UTC by boppudikarthikc

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-04-16 14:26 UTC, matthewfitz commented on modules/dmdIdSystem.js
> +      ? { 'dmdid': value['dmd-dgid'] }
@boppudikarthikc can you camel case this **dmdId**

```
? { 'dmdId': value['dmd-dgid'] }
```

2021-04-16 14:27 UTC, matthewfitz commented on modules/dmdIdSystem.js
> +        return;
@boppudikarthikc Can you snake case the configuration for "api_key"

2021-04-16 16:57 UTC, awerlang commented on modules/dmdIdSystem.js
> +      : null;
Here it must return undefined (see jsdoc above).

2021-04-16 17:21 UTC, awerlang commented
Review this doc: https://github.com/prebid/Prebid.js/blob/master/PR_REVIEW.md#reviewing-a-new-or-updated-user-id-sub-module

It mentions a couple other things are expected:
* Test coverage;
* References added to 4 files under ```modules/```

2021-04-16 18:37 UTC, matthewfitz commented
@boppudikarthikc can you add dmdIdSystem to this submodules registry https://github.com/dmdconnects/Prebid.js/blob/develop/modules/.submodules.json#L23

2021-04-16 20:25 UTC, awerlang commented on modules/userId/eids.js
> +    atype: 1
```dmdid``` i.e. dmd-dgid cookie is a person-based identifier, thus atype = 3 source: https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/AdCOM%20v1.0%20FINAL.md#list_agenttypes

Also, should ```dmdid``` be camel-case?

2021-04-19 20:47 UTC, awerlang requested changes

2021-04-19 20:47 UTC, awerlang commented on modules/dmdIdSystem.js
> +        utils.logError('dmd submodule requires an apiKey.');
typo: apiKey => api_key in the error message.

2021-04-19 20:47 UTC, awerlang commented on test/spec/modules/dmdIdSystem_spec.js
> +  it('should log an error if configParams doesnot have apiKey passed to getId', function () {
typo: apiKey => api_key

2021-04-19 20:47 UTC, awerlang commented on test/spec/modules/dmdIdSystem_spec.js
> +  it('should log an error if configParams has invalid apiKey passed into getId', function () {
typo: apiKey => api_key

2021-04-19 20:47 UTC, awerlang commented on test/spec/modules/dmdIdSystem_spec.js
> +    dmdIdSubmodule.getId({api_key: 123});
```getId()``` expects a ```params``` object containing ```api_key```.

2021-04-19 20:47 UTC, awerlang commented on test/spec/modules/dmdIdSystem_spec.js
> +describe('Dmd ID System', function() {
could you add a positive test case for getId()? Something like ```should call getId() with a valid api_key```

2021-04-20 15:32 UTC, awerlang submitted a review, later dismissed

2021-04-20 18:02 UTC, awerlang approved these changes

2021-04-20 18:53 UTC, matthewfitz approved these changes
Feedback implemented

2021-04-20 18:54 UTC, merged